### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by paulray** [ChiaraMingarelli/gaia_xmatch#1]
Hi,

I think this line is buggy:
```
pm_ra_cosdec = float(d['PMRA'])*np.cos(dec.to(u.rad))*u.mas/u.yr
```
In a TEMPO/Tempo2 par file, PMRA is already mu_alpha*cos(delta), so you should not need to multiply by the cos(dec) again. I'd imagine this is also the case for PM_ELONG, but I haven't verified that.

**Comment by megbedell** [comment]
you're right, thank you!
